version: 2.1
jobs:
  install_deps:
    docker:
      - image: giorgio14/elm-antd-ci:latest
    steps:
      - checkout
      - run:
          name: "Install Showcase Dependencies"
          command: |
            echo "Node version: $(node -v)"
            echo "npm version: $(npm -v)"
            cd ./showcase
            npm install

      - persist_to_workspace:
          root: .
          paths:
            - ./showcase/node_modules

  check_formatting:
    docker:
      - image: giorgio14/elm-antd-ci:latest
    steps:
      - checkout
      - run:
          name: "Check formatting"
          command: |
            echo "> Checking formatting of package"
            elm-format --validate src
            echo "> Checking formatting of showcase"
            elm-format --validate showcase/src/elm

  verify_build:
    docker:
      - image: giorgio14/elm-antd-ci:latest
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: "Build package and showcase"
          command: |
            elm make
            cd showcase
            npm run build

  visual_tests:
    docker:
      - image: giorgio14/elm-antd-ci:latest
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: "Run visual regression tests"
          command: |
            cd showcase
            npm run visual-tests:start-server &>/dev/null &
            # wait for visual testing app to compile
            sleep 5
            npm run visual-tests:run-tests
            
workflows:
  version: 2
  main:
    jobs:
      - install_deps
      - check_formatting
      - verify_build:
          requires:
            - install_deps
      - visual_tests:
          requires:
            - install_deps
